name: 'Run Pylint with reviewdog'
description: '🐶 Run Pylint with reviewdog on pull requests to improve code review experience.'
author: 'dciborow'
inputs:
  workdir:
    description: 'Working directory relative to the root directory.'
    default: '.'
  pylint_rc:
    description: '.pylintrc configuration file'
    default: '.pylintrc'
runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        INPUT_WORKDIR: ${{ inputs.workdir }}
        INPUT_PYLINT_RC: ${{ inputs.pylint_rc }}

# Ref: https://haya14busa.github.io/github-action-brandings/
# TODO: update branding if you want.
branding:
  icon: 'check'
  color: 'blue'
